### ISSUE TITLE
NLTK 3.0.0 compatibility

### ISSUE THREAD

**Issue by interrogator** [wroberts/nltk_tgrep#1]
Hallo,

Your readme example won't work in NLTK 3.0.0

> tree = ParentedTree('(S (NP (DT the) (JJ big) (NN dog)) (VP bit) (NP (DT a) (NN cat)))')
> ParentedTree: Expected a node value and child list

This works, however:

> tree = ParentedTree.fromstring('(S (NP (DT the) (JJ big) (NN dog)) (VP bit) (NP (DT a) (NN cat)))')

**Comment by wroberts** [comment]
Noted in the README (78ff72ce).  Thanks!
